### ISSUE TITLE
New installation: prevents media servers from displaying

### ISSUE THREAD

**Issue by jmorris644** [truckershitch/volumio-plugins#4]
I see that it has been a while since any code updates. Are you still maintaining the plugin?

When I install the plugin, volumio cannot see any local media servers anymore.

I have uninstalled it to test and the media servers show up again.

**Comment by jmorris644** [comment]
A reboot fixed the issue.

**Comment by truckershitch** [comment]
Hey @jmorris644 
The Volumio developers changed the repository name.  You can find current code at https://github.com/truckershitch/volumio-plugins-sources/tree/master/pandora

Note the change from `volumio-plugins` to `volumio-plugins-sources`
